 hosts: all
  become: yes
  vars:
    app_dir: /home/ubuntu/flask_app
    venv_dir: /home/ubuntu/flask_app/venv
    repo_url: "https://github.com/Yashaswininagj/activity1.git"

  tasks:
    - name: Disable SSH host key checking
      lineinfile:
        path: /home/ubuntu/.ssh/config
        line: "StrictHostKeyChecking no"
        create: yes
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Ensure Python3, Pip, and virtualenv are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Ensure correct ownership of app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Create a virtual environment
      command: python3 -m venv "{{ venv_dir }}"
      args:
        creates: "{{ venv_dir }}/bin/activate"

    - name: Install dependencies inside virtual environment
      pip:
        requirements: "{{ app_dir }}/app/requirements.txt"
        virtualenv: "{{ venv_dir }}"

    - name: Create a systemd service for Flask app
      copy:
        dest: /etc/systemd/system/flask_app.service
        content: |
          [Unit]
          Description=Flask Application
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory={{ app_dir }}
          ExecStart={{ venv_dir }}/bin/python3 {{ app_dir }}/app/main.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and enable Flask app service
      systemd:
        daemon_reload: yes
        name: flask_app
        enabled: yes
        state: restarted
